###
GET http://localhost:3000/

###
POST http://localhost:3000/user
Content-Type: application/json

{
  "email": "xuxa@email.com",
  "password": "Abc@123",
  "name": "xuxa"
}

###
GET http://localhost:3000/user/xuxa@email.com

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "xuxa@email.com",
  "password": "Abc@123"
}

###
GET http://localhost:3000/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoieHV4YUBlbWFpbC5jb20iLCJuYW1lIjoieHV4YSIsImlhdCI6MTY2ODU0OTQ3MCwiZXhwIjoxNjcxMTQxNDcwfQ.Wwd56yvgHGZfAH1dx25-nXnot85mweZ0hNyNZ5QuMEk


###
GET http://localhost:3000/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoieHV4YUBlbWFpbC5jb20iLCJuYW1lIjoieHV4YSIsImlhdCI6MTY2ODU0OTQ3MCwiZXhwIjoxNjcxMTQxNDcwfQ.Wwd56yvgHGZfAH1dx25-nXnot85mweZ0hNyNZ5QuMEk