###
GET http://localhost:3000/

###
POST http://localhost:3000/user
Content-Type: application/json

{
  "email": "xuxa@email.com",
  "password": "Abc@123",
  "name": "xuxa"
}

###
GET http://localhost:3000/user/xuxa@email.com

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "xuxa@email.com",
  "password": "Abc@123"
}
